include:
  - project: 'ecocommons-australia/operational-notes-and-scripts/ci-pipelines'
    file: '/v1/supported_ci_ui.yml'
    ref: main

variables:
  CYPRESS_ARGS: "--env split=true"
  BUILD_BSC: 1
  
cypress dev:
  parallel: 1

cypress main:
  parallel: 1
  # Can be enabled to run against Test environment.
  # Currently switched off as some adaptation of tests required.
  #variables:
  #  CYPRESS_ENV_FILE: ".env.test"

