include:
  - project: 'ecocommons-australia/operational-notes-and-scripts/ci-pipelines'
    file: '/v1/supported_ci_ui.yml'
    ref: main
  - project: 'ecocommons-australia/operational-notes-and-scripts/ci-pipelines'
    file: '/v1/supported_ci_ui_bsc.yml'
    ref: develop


# Jest needs some adapting to work with swc/react18
# May be retired enterly...
# unit test:
#   rules:
#     - when: never
#   allow_failure: true

variables:
  CYPRESS_ARGS: "--env split=true"

cypress dev:
  parallel: 3

cypress main:
  parallel: 3


# Can be enabled to run against Test environment 
# Currently switched off.  Some adaptation of pipelines required before this is practical
# Ie, running Dev and Test in develop branch so issues caught early.
# cypress test:
#   variables:
#     USE_CYPRESS_NEXT_ENV_TEST: 1
