include:
  - project: 'ecocommons-australia/operational-notes-and-scripts/ci-pipelines'
    file: '/v1/supported_ci_ui.yml'
    ref: cypress12


# Jest needs some adapting to work with swc/react18
# May be retired enterly...
unit test:
  allow_failure: true

# couple of issues to work out.. check config
# cypress dev:
#   parallel: 3

# cypress main:
#   parallel: 3