version: '3.7'

networks:
  backend:

services:
  nginx:
    image: nginx:1.19
    restart: unless-stopped
    ports:
      - ${APPLICATION_PORT}:80
    volumes:
      - ./deployment/nginx/dev.conf.d:/etc/nginx/conf.d
    networks:
      backend:

  app:
    build:
      context: .
      args:
        NODE_ENV: development
        BUILD_DIR: /srv/app
        NPM_AUTHTOKEN: ${NPM_AUTHTOKEN}
    command: npm run dev
    restart: unless-stopped
    volumes:
      - ./.env:/srv/app/.env
      - ./.env.development:/srv/app/.env.development
      - ./.env.local:/srv/app/.env.local
      - ./.env.development.local:/srv/app/.env.development.local
      - ./components:/srv/app/components
      - ./hooks:/srv/app/hooks
      - ./interfaces:/srv/app/interfaces
      - ./pages:/srv/app/pages
      - ./public:/srv/app/public
      - ./tests:/srv/app/tests
      - ./util:/srv/app/util
    networks:
      backend:
